### ISSUE TITLE
DATAINSIGHT-CHAEBEEN

### ISSUE THREAD

**Issue by chaebeen-A1DATAINT** [A1-Data-Intelligence/GM_LinkBack#8]
PURPOSE
- DATA STRUCTURE INSIGHT

TODO
- DATA relationship INSIGHT
- DATA COLUMS INSIGHT
- DATA imbalanced INSIGHT

DATA
- sample data

**Comment by chaebeen-A1DATAINT** [comment]
LINKBACK column description
- Characterizing Columns
- Organize necessary columns
- Featured column visualization
- Summary of results after internal meeting

NEED
- collation after data acceptance
- working on internal documents

**Comment by Aramir-A1DATAINT** [comment]
internal document after project .
close this docu in 8.16.21
